# Server Configuration
server.port=8080

# Database Connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/financetracker
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations (24 Hours Expiration)
app.jwt.secret=WTNkemRHOXlaeTl0WVdsdUlHUmxiVzlmZEhKaFkydGxiSGx2Ym5RZ2IzSm5aVzVwWlhNZ2RXNWtiM0prWlhJZ1kyOXRjR2x1WldRZ2RXNWtMWEpsWVdOMGIzSjU=
app.jwt.expirationMs=86400000
