# Server Configuration
server.port=8081

# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Configurations for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configurations
app.jwt.secret=WTNkemRHOXlaeTl0WVdsdUlHUmxiVzlmZEhKaFkydGxiSGx2Ym5RZ2IzSm5aVzVwWlhNZ2RXNWtiM0prWlhJZ1kyOXRjR2x1WldRZ2RXNWtMWEpsWVdOMGIzSjU=
app.jwt.expirationMs=86400000
